### ISSUE TITLE
Inconsistency in PointField

### ISSUE THREAD

**Issue by karambir** [Hipo/drf-extra-fields#38]
For gis PointField, we are accepting lat and long as numbers/floats but converting them from model field to json as strings. Here https://github.com/Hipo/drf-extra-fields/blob/master/drf_extra_fields/geo_fields.py#L64-L67

*Input:*

```json
{
        "latitude": 49.8782482189424,
         "longitude": 24.452545489
}
```

*Output:*

```json
{
        "latitude": "49.8782482189424",
         "longitude": "24.452545489"
}
```

Do we have any reasoning for this? I think we should output lat and long as floats.

**Comment by yigitguler** [comment]
Hi @akarambir,

Interesting point. We will investigate.

Thank you!

**Comment by TehQuila** [comment]
I ran into exactly this issue when I tried to instantiate a `django.contrib.gis.geos.Point` with the values of a serialized `PointField` (which obviously fails).

I propose a fix for this issue in this pull request: https://github.com/Hipo/drf-extra-fields/pull/49

**Comment by yigitguler** [comment]
Hi,

I agree that representing geographical locations using floats is the best approach. 

However, it is too late to make such a massive change. This package directly affects the results of the API. If we start using floats instead of strings, the clients that use the projects that use our package will suffer. We should not forget that these API's are not only being consumed by web projects but also mobile (iOS & Android) platforms. It will break the applications of the existing users even if the developers create a new release.

We should follow a backward-compatible approach. 

We can create a new field. FloatPointField maybe?

**Comment by TehQuila** [comment]
Hi @yigitguler,

Sounds reasonable. Can you maybe check with your team how you want to handle this?
I can probably make time to implement a `FloatPointField` but I would appreciate it if I had some certainty that I don't have to spend double effort.

**Comment by yigitguler** [comment]
@alicertel proposed another approach. Assigning this issue to him.

**Comment by alicertel** [comment]
Hi @TehQuila 

We decided to go with the `PointField`. We will prepare a nice release documentation that saying it's not backward compatible anymore. 

To ease the upgrade of the package, a custom attribute can be added to PointField to return points in string instead of float .

Sample usage would be `PointField(str_points=True)`. All they have to do to add str_points=True to the field. By default this is going to be false.

How that sounds?

**Comment by TehQuila** [comment]
Hi @alicertel 

Sounds good to me, I'll see when I can get started and update my PR accordingly.

**Comment by TehQuila** [comment]
hey @alicertel, I updated my PR accordingly, hopefully to your liking.

**Comment by alicertel** [comment]
Fixed with https://github.com/Hipo/drf-extra-fields/pull/49
