### ISSUE TITLE
Image Can't be determined

### ISSUE THREAD

**Issue by bobozar** [Hipo/drf-extra-fields#56]
I'm want to upload an image via json. My image path is 

`photo = '/media/profile/avatars/2018/06/22/aka.jpg'`

So I did

```
>>> values = { 'photo':photo'}    
>>> man= requests.post(URL_EDIT, data=json.dumps(values), headers=after_header)
>>> man		    
<Response [400]>
>>> man.text
'{"photo":["The type of the image couldn\'t be determined."]}'

```
Serializer

`photo = Base64ImageField(required=False)`

`>>> my header is after_header = {'Content-Type':'application/json', 'Authorization':'Token {}'.format('c641df5')}`

**Comment by jeverling** [comment]
Hi, what you send to the API is not your image, but rather the path to it (a string). 

Try something like this:

```python
from base64 import b64encode
import requests


photo = '/media/profile/avatars/2018/06/22/aka.jpg'

with open(photo, 'rb') as image_file:
    encoded_string = b64encode(image_file.read())

# we need to decode the bytestring returned by b64encode to get a string that is JSON serializable
values = {'photo': encoded_string.decode()}    

man = requests.post(URL_EDIT, data=json.dumps(values), headers=after_header)

```

Alternatively, you could send the image file as `multipart/form-data`, either using [HybridImageField](https://github.com/Hipo/drf-extra-fields/blob/master/drf_extra_fields/fields.py#L102) or the standard DRF `ImageField`.
But with `Base64ImageField` you need to encode your image file with *base64* before sending it as part of a JSON object. This will increase the file-size by about 30%, so if bandwith is an issue you might consider sending the request as `multipart/form-data` instead of JSON that includes a base64 encoded file.
